/**
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
 * 
 */

// ================================================================================
//    FUNCTIONS
// ================================================================================

const nextTriangleNumber = (current = 0, nextIndex = 1) => current + nextIndex;
const countFactors = num => {
	var count = 2; // itself and 1
	var limit = num >> 2;
	var oppFactor = num;
	for(var i = 2; i < limit; i++) {
		if(oppFactor < i) {
			break;
		} else if(Number.isInteger(oppFactor = num / i)) {
			if(i == oppFactor) {
				count++;
				break;
			}
			count += 2;
		}
	}

	return count;
};


// ================================================================================
//    CONSTANTS
// ================================================================================

const FACTOR_GOAL = 500;



// ================================================================================
//    ANSWER
// ================================================================================

const answer = () => {
	var current = 1;
	for(var i = 2;; i++) {
		current = nextTriangleNumber(current, i);
		const count = countFactors(current);
		if(count >= FACTOR_GOAL) {
			return current;
		}
	}
};

console.log(answer());
